apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: tempo_ds
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus_ds
      nodeGraph:
        enabled: true
      # traceToLogs:
      #   datasourceUid: loki_ds
      #   tags: ["http.url", "service.name", "trace_id"]
      traceToMetrics:
        datasourceUid: prometheus_ds
        queries:
          - name: "HTTP Calls"
            query: 'rate(http_server_duration_seconds_count{service_name="$service.name"}[$__range])'
    readOnly: false